version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        USERNAME: "coolseaweed" # default: docker
        USER_UID: 1001 # default: 1000
        USER_GID: 100 # default: 1000
    
    user: "coolseaweed"
    working_dir: /home/coolseaweed/
    volumes:
      - /home/coolseaweed/:/home/coolseaweed/

    tty: true
    command: /bin/bash
