# .github/workflows/review-pr.yml
# Latest Created: 2024-06-26 16:30:00
name: Auto Code Review
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write # PR 리뷰 작성에 필요
  contents: read # PR 내용 분석에 필요
  id-token: write # claude-code-action OIDC 인증에 필요

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: experimental-review
          custom_instructions: |
            변경 내용을 코드 품질, 보안, 성능 관점에서 리뷰해주세요
            Critical 이슈가 있다면 반드시 지적해주세요
            리뷰는 한국어로 작성해주세요
